services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=$NAME
      - POSTGRES_USER=$USER
      - POSTGRES_PASSWORD=$PASSWORD
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL","pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/db:/var/lib/postgresql/14/main

  web:
    build:
      context: .
    command: /bin/bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    environment:
      - DEBUG=1
      - SECRET_KEY=$SECRET_KEY
      - DJANGO_ALLOWED_HOSTS=['*']
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db:
    driver: local